[package]
edition = '2021'
name = 'neatpic'
version = '0.1.0'

[dependencies]
dirs = '4'
egui-macroquad = '0.12.0'
image = '0.24.4'
serde.features = ['derive']
serde.version = '1'
serde_yaml = '0.9.13'
